task/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'webapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

webapp/urls.py
from django.urls import path
from webapp.views.project_view import (ProjectListView, ProjectDetailView, ProjectCreateView,
                                       ProjectUpdateView, ProjectDeleteView, UpdateUserView)
from webapp.views.task_views import TaskCreateView, TaskUpdateView, TaskDeleteView, TaskDetailView
from django.views.generic import RedirectView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),
    path('project/', RedirectView.as_view(pattern_name='webapp:home')),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='detail_project'),
    path('projects/<int:pk>/update/', ProjectUpdateView.as_view(), name='update_project'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete_project'),
    path('projects/add/', ProjectCreateView.as_view(), name='create_project'),
    path('task/<int:pk>/', TaskDetailView.as_view(), name='task_view'),
    path('task/<int:pk>/add/', TaskCreateView.as_view(), name='create_task'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='update_task'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete_task'),
    path('projects/<int:pk>/users/update/', UpdateUserView.as_view(), name='update_user'),
]

webapp/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.shortcuts import reverse

class Type(models.Model):
    name = models.CharField(verbose_name='Название', max_length=150)

    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.CharField(verbose_name='Название', max_length=150)

    def __str__(self):
        return self.name

def validate_summary(value):
    if len(value) <= 8:
        raise ValidationError('Ваш summary заголовок слишкм кароткий. Не менее 8 символов')

def validate_description(value):
    if 'rich forever' in value.lower():
        raise ValidationError('Недопустимое слово в описании')

class Task(models.Model):
    summary = models.CharField(verbose_name='Краткое описание', max_length=200, validators=[validate_summary])
    description = models.TextField(verbose_name='Полное описание', max_length=500, null=True, blank=True, validators=[validate_description])
    status = models.ForeignKey('webapp.Status', verbose_name='Статус', on_delete=models.RESTRICT)
    type = models.ManyToManyField('webapp.Type', related_name='tasks', verbose_name='Тип')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, verbose_name='Проект')
    created_date = models.DateTimeField(verbose_name='Дата и время создания', auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name='Дата и время обновления', auto_now=True)

class Project(models.Model):
    name = models.CharField(verbose_name='Название', max_length=250)
    description = models.TextField(verbose_name='Опсиание', max_length=400, )
    users = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Пользователи', null=True, blank=True)
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата конца', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('webapp:detail_project', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model

from webapp.models import Task, Project

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['summary', 'description', 'status', 'type']
        widgets = {'type': forms.CheckboxSelectMultiple}

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date']
        widgets = {'users': forms.CheckboxSelectMultiple}


class ProjectUserForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['users']
        widgets = {'users': forms.CheckboxSelectMultiple}

class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=150, required=False, label='Поиск')

webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from webapp.models import Task
from django.views.generic import View, TemplateView
from webapp.forms import TaskForm


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        return context


class TaskView(TemplateView):
    template_name = 'task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = get_object_or_404(Task, pk=kwargs.get('pk'))
        return context


class TaskCreateView(View):
    def get(self, requset, *args, **kwargs):
        form = TaskForm()
        return render(requset, 'create_task.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'create_task.html', {'form': form})


class TaskUpdateView(TemplateView):
    template_name = 'update_task.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        form = TaskForm(initial={
            'summary': task.summary,
            'description': task.description,
            'status': task.status,
            'type': task.type.all(),
        })
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        form = TaskForm(data=request.POST)
        if form.is_valid():
            types = form.cleaned_data.pop('type')
            task.summary = form.cleaned_data.get('summary')
            task.description = form.cleaned_data.get('description')
            task.status = form.cleaned_data.get('status')
            task.type.set(types)
            task.save()
            return redirect('home')
        else:
            return render(request, 'update_task.html', {'form': form})

class TaskDeleteView(View):
    def get(self, requset, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        return render(requset, 'task_delete.html', {'task': task})

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        task.delete()
        return redirect('home')

webapp/views/project_view.py
from urllib.parse import urlencode
from django.shortcuts import reverse, redirect, get_object_or_404
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from webapp.forms import SimpleSearchForm, ProjectForm, ProjectUserForm
from webapp.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/home.html'
    context_object_name = 'projects'
    paginate_by = 5

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.get_search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects/detail_project.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.get_object()

        context['tasks'] = project.task_set.all()
        return context

class ProjectCreateView(PermissionRequiredMixin, CreateView):
    model = Project
    template_name = 'projects/create_project.html'
    form_class = ProjectForm
    permission_required = 'webapp.add_project'

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)
        form.instance.users.add(self.request.user)
        return response


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'projects/project_update.html'
    form_class = ProjectForm
    permission_required = 'webapp.change_project'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().has_permission() and self.request.user in project.users.all() or self.request.user == self.get_object().users

    def get_success_url(self):
        return reverse('webapp:home')

class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'projects/project_delete.html'

    def get_success_url(self):
        return reverse('webapp:home')


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectUserForm
    template_name = 'update_user.html'
    context_object_name = 'project'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('webapp:detail_project', kwargs={'pk': self.object.pk})

webapp/views/task_views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from webapp.models import Task, Project
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import TaskForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_view.html'

class TaskCreateView(PermissionRequiredMixin, CreateView):
    form_class = TaskForm
    template_name = 'tasks/create_task.html'
    permission_required = 'webapp.add_task'

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        form.save_m2m()
        return redirect('webapp:detail_project', pk=project.pk)


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks/task_delete.html'
    permission_required = 'webapp.delete_task'

    def get_success_url(self):
        return reverse('webapp:detail_project', kwargs={'pk': self.object.project.pk})

class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update_task.html'
    permission_required = 'webapp.update_task'

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})

webapp/templates/tasks/create_task.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:home' %}">Home page</a>
{% endblock %}

    <title>{% block title %}Create{% endblock %}</title>

{% block content %}
<h1 style="margin-top: 50px; margin-bottom: 50px">Add new Task</h1>
<form method="post" action="">
    {% include 'partial/create_update_form.html' with value_submit='Добавить' %}
</form>
{% endblock %}

webapp/templates/tasks/task_delete.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:home' %}">Home page</a>
{% endblock %}


<title>{% block title %}Delete{% endblock %}</title>

{% block content %}
    <h1 style="margin-top: 50px; margin-bottom: 50px">Are you sure you want to delete!? </h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Yes</button>
        <a class="btn btn-danger" href="{% url 'webapp:task_view' task.pk %}" role="button">No</a>
    </form>
{% endblock %}

webapp/templates/tasks/task_view.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:home' %}">Home page</a>
    <span style="margin-top: 8px">|</span>
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:detail_project' task.project.pk %}">On Projects</a>
    <span style="margin-top: 8px">|</span>
    {% if perms.webapp.add_task and request.user in project.users.all%}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:create_task' task.pk %}">Add Task</a>
    {% endif %}
    <span style="margin-top: 8px">|</span>
    {% if perms.webapp.update_task and request.user in project.users.all%}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:update_task' task.pk %}">Redact</a>
    {% endif %}
    {% if perms.webapp.delete_task and request.user in project.users.all%}
    <span style="margin-top: 8px">|</span>
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:delete_task' task.pk %}">Delete</a>
    {% endif %}
{% endblock %}

<title>{% block title %}Details{% endblock %}</title>

{% block content %}
    <h1 style="margin-top: 50px; margin-bottom: 50px">Details:</h1>
    <div class="card border-dark mb-3" style="max-width: 18rem;">
        <div class="card-header bg-transparent border-dark"><b>{{ task.summary }}</b></div>
        <div class="card-body">
            <h5 class="card-title">{{ task.description }}</h5>
            <h6 class="card-text">Type: {% for type in task.type.all %}
                {{ type.name }}{% if forloop.last %}.{% else %},{% endif %}
            {% endfor %}
            </h6>
            <h6 class="card-text">Status: {{ task.status.name }}</h6>
        </div>
        <div class="card-footer bg-transparent border-success"><b>{{ task.created_date }}</b></div>
    </div>
{% endblock %}

webapp/templates/tasks/update_task.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:home' %}">Home page</a>
    <span style="margin-top: 8px">|</span>
    <a class="nav-link active" aria-current="page" href="{% url 'webapp:detail_project' task.project.pk %}">On Projects</a>
{% endblock %}

    <title>{% block title %}Update{% endblock %}</title>

{% block content %}

<h1 style="margin-top: 50px; margin-bottom: 50px">Update your Task</h1>
<form method="post">
    {% include 'partial/create_update_form.html' with value_submit='Заменить' %}
</form>
{% endblock %}